In [1]:
import numpy as np
import pandas as pd
import torch

* Accessing the GPU
* Running Tensors and pytorch objects on GPU and making faster computations
  

### getting a gpu
1. By google colab --(upgrade for better)
2. In Built GPU
3. Cloud Computing- GCP,Aws,Azure allow to rent comp and access them

In [3]:
## check with the gpu access

In [5]:
torch.cuda.is_available()

False

In [7]:
torch.backends.mps.is_available()

True

In [8]:
# setup device agostic code


In [10]:
torch.backends.mps.is_available()

True

In [11]:
tensor=torch.tensor([1,2,3])

In [14]:
tensor,tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [21]:
#this will  produce new variable on gpu
tensor_on_gpu=tensor.to("mps")

In [22]:
tensor.device

device(type='cpu')

In [23]:
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')

In [24]:
## moving back to cpu

In [25]:
tocpu=tensor_on_gpu.numpy()
# cant convert to the numpy when in gpu

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [26]:
tocpu=tensor_on_gpu.to("cpu")

In [28]:
tocpu,tocpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [29]:
tocpu.numpy()

array([1, 2, 3])