In [1]:
import pandas as pd 
import torch

In [4]:
#check the cpu and gpu version


In [5]:
# Pytorch funcdamentals

In [7]:
print(torch.__version__)

2.4.1


In [8]:
print(torch.__version__)

2.4.1


In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

In [10]:
#cu111  cuda 11

In [12]:
## introduction to tensors
## main building block of the data

In [13]:
#multidimentional data

In [14]:
# creating the tensor

In [15]:
#scaler

In [16]:
scaler=torch.tensor(7)

In [17]:
scaler

tensor(7)

In [19]:
type(scaler)

torch.Tensor

In [20]:
torch.Tensor

torch.Tensor

In [21]:
torch.tensor(10.4)

tensor(10.4000)

In [22]:
mat=torch.tensor([[1,2,3],[4,5,6]])

In [23]:
mat

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
scaler.ndim
#they are tensor domentions not wrt to the matrices

0

In [26]:
mat.ndim

2

In [27]:
vec=torch.tensor([1,2,3])

In [28]:
vec.ndim

1

In [29]:
#scaler tensor 0
#vector tensor 1
#2-d array tensor 2

In [30]:
scaler.item()

7

In [32]:
mat

tensor([[1, 2, 3],
        [4, 5, 6]])

In [33]:
vector=torch.tensor([7,7])

In [34]:
vector

tensor([7, 7])

In [35]:
vector.ndim

1

In [36]:
mat.ndim

2

In [37]:
vector.shape

torch.Size([2])

In [39]:
vector.size()

torch.Size([2])

In [40]:
mat.size()

torch.Size([2, 3])

In [41]:
mat

tensor([[1, 2, 3],
        [4, 5, 6]])

In [42]:
mat.ndim

2

In [43]:
mat[0]

tensor([1, 2, 3])

In [44]:
mat[0][0]

tensor(1)

In [45]:
mat[1]

tensor([4, 5, 6])

In [49]:
mat.shape

torch.Size([2, 3])

In [50]:
mat.size()

torch.Size([2, 3])

In [52]:
mat.shape[1]

3

TENSOR=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]

In [54]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [55]:
TENSOR


tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [56]:
TENSOR.ndim

3

In [57]:
TENSOR.shape

torch.Size([2, 2, 3])

In [59]:
TENSOR.size()

torch.Size([2, 2, 3])

In [60]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [61]:
TENSOR[1]

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [62]:
TENSOR.shape

torch.Size([2, 2, 3])

In [63]:
#the above means two 2*3 matrices

In [64]:
#now lets see about the generating the random values of the tensors

In [65]:
TENSOR.shape

torch.Size([2, 2, 3])

In [66]:
#generally scalers and vectors will be a lower case and matrices and tensors will be the uppercase

In [67]:
### Random tensors

# random tensors were iportant were important as many neural networks learn from the random numbers and learn grom the data but they 
start with the random numbers and update them with the algorithm

In [68]:
#random tensor of size(3,4)

In [69]:
random=torch.rand(3,4)

In [70]:
random

tensor([[0.2583, 0.1805, 0.7388, 0.0761],
        [0.5142, 0.2955, 0.3835, 0.2685],
        [0.7492, 0.4500, 0.6631, 0.5342]])

In [71]:
random.ndim

2

In [81]:
r=torch.rand(3)

In [82]:
r

tensor([0.6410, 0.1908, 0.3557])

In [83]:
newrandom=torch.rand(2,10,10)

In [84]:
newrandom

tensor([[[0.7048, 0.8654, 0.4916, 0.2396, 0.2061, 0.6574, 0.3809, 0.4269,
          0.7503, 0.5258],
         [0.2861, 0.3411, 0.0660, 0.3091, 0.9602, 0.8272, 0.1463, 0.6438,
          0.1589, 0.0442],
         [0.2756, 0.8192, 0.3820, 0.3183, 0.4832, 0.3109, 0.9177, 0.8982,
          0.0172, 0.6019],
         [0.0086, 0.2290, 0.6829, 0.8495, 0.9185, 0.4671, 0.7706, 0.7973,
          0.1466, 0.1370],
         [0.8102, 0.4159, 0.3651, 0.6930, 0.0381, 0.6225, 0.3388, 0.4149,
          0.0726, 0.1909],
         [0.7454, 0.1836, 0.8441, 0.7360, 0.5939, 0.0437, 0.0032, 0.4971,
          0.6312, 0.5858],
         [0.1728, 0.6873, 0.5671, 0.0459, 0.8481, 0.8622, 0.2926, 0.1976,
          0.6033, 0.8729],
         [0.4741, 0.7785, 0.5430, 0.2162, 0.2137, 0.5468, 0.5796, 0.7495,
          0.2893, 0.3149],
         [0.9749, 0.9710, 0.0483, 0.7976, 0.0574, 0.2234, 0.9168, 0.8292,
          0.4808, 0.0180],
         [0.4321, 0.3922, 0.9456, 0.4680, 0.8734, 0.2893, 0.4081, 0.2402,
          0.0699,

In [86]:
sample=torch.rand(10,10,10)

In [87]:
sample

tensor([[[5.1472e-01, 2.5805e-02, 5.4707e-01, 6.2110e-01, 1.1825e-01,
          5.3945e-01, 7.5378e-01, 6.7925e-01, 9.7352e-01, 9.2949e-01],
         [4.8783e-01, 8.4549e-01, 4.0712e-01, 7.9160e-01, 3.4946e-01,
          2.1775e-01, 2.1885e-01, 6.9305e-01, 7.4716e-01, 9.1792e-01],
         [3.4621e-02, 5.5566e-01, 4.2954e-01, 9.3969e-01, 7.8920e-01,
          8.0863e-01, 7.1033e-01, 1.5564e-02, 7.4295e-01, 1.9301e-01],
         [7.8526e-01, 5.4490e-01, 7.4616e-02, 7.5142e-01, 5.2790e-01,
          2.7982e-01, 9.7616e-01, 2.9490e-01, 2.6170e-01, 2.1441e-01],
         [5.5139e-01, 3.3884e-01, 7.4070e-01, 1.0468e-01, 3.8177e-01,
          7.7207e-01, 2.4107e-01, 5.4333e-01, 5.7357e-01, 1.5901e-01],
         [9.3245e-01, 2.8027e-01, 6.6386e-01, 7.8721e-01, 5.8313e-01,
          3.2406e-01, 2.3883e-01, 7.3059e-01, 9.3329e-01, 8.5513e-01],
         [8.1436e-01, 1.9912e-01, 6.5204e-01, 6.6144e-02, 5.4443e-01,
          9.8518e-01, 1.0987e-01, 7.9214e-01, 6.4263e-01, 4.2096e-01],
         [8.5

In [88]:
sample.ndim

3

In [89]:
random

tensor([[0.2583, 0.1805, 0.7388, 0.0761],
        [0.5142, 0.2955, 0.3835, 0.2685],
        [0.7492, 0.4500, 0.6631, 0.5342]])

In [90]:
# random tensor similar to image tensor

In [98]:
random_img=torch.rand(size=(3,224,224))  #colorchannel,height,width

In [99]:
random_img.shape

torch.Size([3, 224, 224])

In [101]:
#we have the color channel wil have the 3rd dimention 

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


### The random numbers in the pytorch was more important as the neural network were initiated with the random numbers and then updated with respect to the algorithm

`torch.rand(size=(z,x,y))`

In [103]:
s=torch.rand(100,100,10000)

In [104]:
s.ndim

3

In [105]:
s.shape

torch.Size([100, 100, 10000])

In [106]:
zero=torch.zeros(3,4)

In [107]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [108]:
r=torch.rand(3,4)

In [109]:
zero*r

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [112]:
zero.ndim


2

In [114]:
ones=torch.ones(3,4)

In [115]:
ones*r

tensor([[0.0852, 0.9172, 0.1660, 0.2975],
        [0.9387, 0.6631, 0.2943, 0.5025],
        [0.1446, 0.4072, 0.3302, 0.7156]])

In [116]:
ones.dtype

torch.float32

In [120]:
ones.dtype

torch.float32

In [121]:
# we can create the random values in many ways but rand() was most common way

In [122]:
#tensors in a range()