In [1]:
import pandas as pd 
import torch

In [2]:
#check the cpu and gpu version


In [3]:
# Pytorch funcdamentals

In [4]:
print(torch.__version__)

2.4.1


In [5]:
print(torch.__version__)

2.4.1


In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

In [7]:
#cu111  cuda 11

In [8]:
## introduction to tensors
## main building block of the data

In [9]:
#multidimentional data

In [10]:
# creating the tensor

In [11]:
#scaler

In [12]:
scaler=torch.tensor(7)

In [13]:
scaler

tensor(7)

In [14]:
type(scaler)

torch.Tensor

In [15]:
torch.Tensor

torch.Tensor

In [16]:
torch.tensor(10.4)

tensor(10.4000)

In [17]:
mat=torch.tensor([[1,2,3],[4,5,6]])

In [18]:
mat

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
scaler.ndim
#they are tensor domentions not wrt to the matrices

0

In [20]:
mat.ndim

2

In [21]:
vec=torch.tensor([1,2,3])

In [22]:
vec.ndim

1

In [23]:
#scaler tensor 0
#vector tensor 1
#2-d array tensor 2

In [24]:
scaler.item()

7

In [25]:
mat

tensor([[1, 2, 3],
        [4, 5, 6]])

In [26]:
vector=torch.tensor([7,7])

In [27]:
vector

tensor([7, 7])

In [28]:
vector.ndim

1

In [29]:
mat.ndim

2

In [30]:
vector.shape

torch.Size([2])

In [31]:
vector.size()

torch.Size([2])

In [32]:
mat.size()

torch.Size([2, 3])

In [33]:
mat

tensor([[1, 2, 3],
        [4, 5, 6]])

In [34]:
mat.ndim

2

In [35]:
mat[0]

tensor([1, 2, 3])

In [36]:
mat[0][0]

tensor(1)

In [37]:
mat[1]

tensor([4, 5, 6])

In [38]:
mat.shape

torch.Size([2, 3])

In [39]:
mat.size()

torch.Size([2, 3])

In [40]:
mat.shape[1]

3

TENSOR=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]

In [41]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [42]:
TENSOR


tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [43]:
TENSOR.ndim

3

In [44]:
TENSOR.shape

torch.Size([2, 2, 3])

In [45]:
TENSOR.size()

torch.Size([2, 2, 3])

In [46]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [47]:
TENSOR[1]

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [48]:
TENSOR.shape

torch.Size([2, 2, 3])

In [49]:
#the above means two 2*3 matrices

In [50]:
#now lets see about the generating the random values of the tensors

In [51]:
TENSOR.shape

torch.Size([2, 2, 3])

In [52]:
#generally scalers and vectors will be a lower case and matrices and tensors will be the uppercase

In [53]:
### Random tensors

# random tensors were iportant were important as many neural networks learn from the random numbers and learn grom the data but they 
start with the random numbers and update them with the algorithm

In [54]:
#random tensor of size(3,4)

In [55]:
random=torch.rand(3,4)

In [56]:
random

tensor([[0.4784, 0.8022, 0.9258, 0.7209],
        [0.9020, 0.4699, 0.7885, 0.5973],
        [0.1524, 0.9205, 0.3642, 0.3179]])

In [57]:
random.ndim

2

In [58]:
r=torch.rand(3)

In [59]:
r

tensor([0.3636, 0.2762, 0.7580])

In [60]:
newrandom=torch.rand(2,10,10)

In [61]:
newrandom

tensor([[[0.0770, 0.5835, 0.6223, 0.2572, 0.9682, 0.3342, 0.7975, 0.2751,
          0.8053, 0.9081],
         [0.3820, 0.0381, 0.7868, 0.4983, 0.0764, 0.5556, 0.0568, 0.2154,
          0.6767, 0.7996],
         [0.8070, 0.0571, 0.5758, 0.4023, 0.7798, 0.7685, 0.1917, 0.1555,
          0.1603, 0.1099],
         [0.7481, 0.1218, 0.8850, 0.4861, 0.1201, 0.9802, 0.5538, 0.2930,
          0.3834, 0.3155],
         [0.3988, 0.2702, 0.8739, 0.3053, 0.7245, 0.7431, 0.2373, 0.7340,
          0.3768, 0.8934],
         [0.3077, 0.5218, 0.6455, 0.8995, 0.9921, 0.8001, 0.2731, 0.3174,
          0.8231, 0.7744],
         [0.2098, 0.3070, 0.9071, 0.7739, 0.9959, 0.2564, 0.3949, 0.3982,
          0.2906, 0.6957],
         [0.8373, 0.4850, 0.8372, 0.5919, 0.7317, 0.4257, 0.9313, 0.5853,
          0.9454, 0.3696],
         [0.1765, 0.2858, 0.9196, 0.3539, 0.7796, 0.0078, 0.0845, 0.1547,
          0.3047, 0.4951],
         [0.8002, 0.7352, 0.6239, 0.8189, 0.7656, 0.1031, 0.8483, 0.4470,
          0.2632,

In [62]:
sample=torch.rand(10,10,10)

In [63]:
sample

tensor([[[0.2231, 0.3636, 0.9013, 0.4770, 0.4871, 0.0031, 0.1864, 0.7036,
          0.0740, 0.3758],
         [0.9385, 0.2860, 0.7155, 0.9041, 0.9453, 0.6092, 0.5901, 0.7169,
          0.2914, 0.7186],
         [0.4978, 0.1720, 0.9159, 0.8447, 0.0897, 0.2478, 0.3532, 0.9632,
          0.7615, 0.1024],
         [0.0626, 0.1458, 0.4894, 0.5337, 0.8397, 0.8765, 0.5515, 0.7531,
          0.6716, 0.8211],
         [0.0244, 0.6301, 0.8101, 0.1503, 0.2261, 0.1391, 0.6505, 0.1273,
          0.9066, 0.9258],
         [0.9541, 0.1162, 0.8772, 0.8458, 0.6340, 0.0650, 0.4940, 0.2361,
          0.4127, 0.6311],
         [0.3615, 0.0839, 0.1487, 0.2454, 0.0461, 0.8831, 0.4819, 0.6897,
          0.5369, 0.9878],
         [0.3358, 0.3802, 0.7855, 0.0308, 0.2242, 0.3361, 0.4422, 0.9700,
          0.6631, 0.3690],
         [0.5996, 0.6538, 0.6182, 0.7757, 0.8271, 0.4979, 0.7056, 0.8018,
          0.6229, 0.6680],
         [0.0466, 0.5298, 0.9974, 0.5660, 0.8794, 0.5350, 0.6957, 0.8937,
          0.7065,

In [64]:
sample.ndim

3

In [65]:
random

tensor([[0.4784, 0.8022, 0.9258, 0.7209],
        [0.9020, 0.4699, 0.7885, 0.5973],
        [0.1524, 0.9205, 0.3642, 0.3179]])

In [66]:
# random tensor similar to image tensor

In [67]:
random_img=torch.rand(size=(3,224,224))  #colorchannel,height,width

In [68]:
random_img.shape

torch.Size([3, 224, 224])

In [69]:
#we have the color channel wil have the 3rd dimention 

### The random numbers in the pytorch was more important as the neural network were initiated with the random numbers and then updated with respect to the algorithm

`torch.rand(size=(z,x,y))`

In [70]:
s=torch.rand(100,100,10000)

In [71]:
s.ndim

3

In [72]:
s.shape

torch.Size([100, 100, 10000])

In [73]:
zero=torch.zeros(3,4)

In [74]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [75]:
r=torch.rand(3,4)

In [76]:
zero*r

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [77]:
zero.ndim


2

In [78]:
ones=torch.ones(3,4)

In [79]:
ones*r

tensor([[0.8617, 0.1907, 0.0327, 0.8515],
        [0.5378, 0.5905, 0.0655, 0.6990],
        [0.3720, 0.1661, 0.5754, 0.8358]])

In [80]:
ones.dtype

torch.float32

In [81]:
ones.dtype

torch.float32

In [82]:
# we can create the random values in many ways but rand() was most common way

In [83]:
#tensors in a range()

In [84]:
ran=torch.rand(300,100,100)

In [85]:
torch.tensor(2)

tensor(2)

In [86]:
torch.tensor([1,2,3]).shape

torch.Size([3])

In [87]:
### create a range of tensors and tensor-like

In [88]:
torch.range(1,100,1)
# as the range as not available with the pytorch anymore use the arange which is similar to 

/var/folders/4m/q_kqcf711rs2gm0dt1z3kv3w0000gn/T/ipykernel_1138/3470486478.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,100,1)


tensor([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
         13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
         25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
         37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,
         49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
         61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
         73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,
         85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
         97.,  98.,  99., 100.])

In [89]:
a=torch.arange(1,100,1)

In [90]:
a.shape

torch.Size([99])

In [91]:
a.size()

torch.Size([99])

In [92]:
a.ndim

1

In [93]:
a.dtype

torch.int64

In [94]:
one_to_ten=torch.arange(1,11,1)

In [95]:
torch.arange(0,1000,77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [96]:
#to be more specific we can use the folllowing use case

In [97]:
torch.arange(start=1,end=1000,step=1)

tensor([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
         15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
         57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
         71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
         99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
        155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 1

In [98]:
torch.__version__

'2.4.1'

In [99]:
#tensors like

In [100]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
ten=torch.zeros_like(one_to_ten)

In [102]:
ten

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [103]:
ones=torch.ones_like(random)

In [104]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [105]:
ones.dtype

torch.float32

In [106]:
# default dtype id float32

In [107]:
### tensor datatypes

In [108]:
#float tensors 

In [109]:
float32=torch.tensor([3.0,2.9,5.6],dtype=None)

In [110]:
float32

tensor([3.0000, 2.9000, 5.6000])

In [111]:
float32.dtype

torch.float32

In [112]:
#default datatype was float32

In [113]:
float2=torch.tensor([1.0,2.4,3.9,5],dtype=torch.float16)

In [114]:
float2

tensor([1.0000, 2.4004, 3.9004, 5.0000], dtype=torch.float16)

In [115]:
float2.dtype

torch.float16

In [116]:
int3=torch.tensor([1,2,4.5],dtype=torch.int32)

In [117]:
int3

tensor([1, 2, 4], dtype=torch.int32)

In [118]:
data=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)

In [119]:
data
# we have to define the space how it was stores for better precision and speed
# how much detail that a number conisist of


tensor([3., 6., 9.])

In [120]:
# datatypes are the one of the three big errord we may fall while developing

In [121]:
# device="cpu" by default but we can set to cuda

In [122]:
# if one tensor on cpu and another on gpu it will throw the error

In [123]:
gd=torch.tensor([2.0,4.0,6.0])

In [124]:
# device will tell about the which device we are running on

In [125]:
#requires_grad will tell us wether we need to track gradient or not

In [126]:
float2=float32.type(torch.float16)

In [127]:
float2

tensor([3.0000, 2.9004, 5.6016], dtype=torch.float16)

# Problems could be expected
#### datatypes were not same
#### varaibles wee on diffweent device
####  different shape

In [128]:
float2*float32

tensor([ 9.0000,  8.4111, 31.3687])

In [129]:
#but it worked in sometimes in large neural networks will create a problem

In [130]:
int_32=torch.tensor([1.4,2,4.9],dtype=torch.int32)

In [131]:
int_32

tensor([1, 2, 4], dtype=torch.int32)

In [132]:
float2

tensor([3.0000, 2.9004, 5.6016], dtype=torch.float16)

In [133]:
float2*int_32

tensor([ 3.0000,  5.8008, 22.4062], dtype=torch.float16)

In [134]:
# but it stil worked as well but still its a problem in large neuranetwork

In [135]:
long=torch.tensor([1,2,3],dtype=torch.long)

In [136]:
long*float2

tensor([ 3.0000,  5.8008, 16.8125], dtype=torch.float16)

In [137]:
# its is more robust


In [138]:
### getting info from the tensor

## to get the datatype we can use the `tensor.dtype`

## to get the device `tensor.device`

## for the shape  `tensor.shape`

In [139]:
int_32.device

device(type='cpu')

In [140]:
sample=torch.rand(3,4)

In [142]:
print(sample)

tensor([[0.3977, 0.9743, 0.4116, 0.7244],
        [0.7547, 0.6139, 0.4881, 0.5595],
        [0.1488, 0.3119, 0.4717, 0.6500]])


sample.ndim

In [143]:
sample.ndim

2

In [144]:
sample.shape

torch.Size([3, 4])

In [145]:
sample.size()

torch.Size([3, 4])

In [146]:
###.ndim tensor .shape  .size()  .rand etc

In [147]:
## .size() and .shape will give the same output

In [149]:
print(sample)
print(f'the dimention of sample {sample.ndim}')
print(f'the shape of the sample {sample.shape}')
print(f'the device in which it is in {sample.device}')

tensor([[0.3977, 0.9743, 0.4116, 0.7244],
        [0.7547, 0.6139, 0.4881, 0.5595],
        [0.1488, 0.3119, 0.4717, 0.6500]])
the dimention of sample 2
the shape of the sample torch.Size([3, 4])
the device in which it is in cpu


In [150]:
#all the tensor we create will be default in cpu we have to specify for storing in gpu

In [151]:
## how to change the device while the program was running

In [152]:
## manipulating the tensors