In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### The manipulations in Pytorch:
1.Addition
2.Subtraction
3.Multiplication(element-wise)
4.Division
5.Matrix Multiplication

In [2]:
sample1=torch.tensor([1,2,3])


In [3]:
sample1+10

tensor([11, 12, 13])

In [5]:
sample1

tensor([1, 2, 3])

In [6]:
sample1+100

tensor([101, 102, 103])

In [7]:
sample1*10

tensor([10, 20, 30])

In [8]:
sample1/2

tensor([0.5000, 1.0000, 1.5000])

In [9]:
sample1=sample1*10

In [10]:
sample1

tensor([10, 20, 30])

In [11]:
# subtract 10


In [12]:
sample1-10

tensor([ 0, 10, 20])

In [13]:
sample1-20

tensor([-10,   0,  10])

In [14]:
## Try out pytorch inbuilt function

In [15]:
torch.mul(sample1,10)

tensor([100, 200, 300])

In [16]:
torch.add(sample1,200)

tensor([210, 220, 230])

In [17]:
torch.sub(sample1,1)

tensor([ 9, 19, 29])

In [18]:
torch.div(sample1,2)

tensor([ 5., 10., 15.])

In [19]:
sample1

tensor([10, 20, 30])

In [20]:
## matrix multiplication