In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### The manipulations in Pytorch:
1.Addition
2.Subtraction
3.Multiplication(element-wise)
4.Division
5.Matrix Multiplication

In [4]:
sample1=torch.tensor([1.3,2,3])


In [5]:
sample1+10

tensor([11.3000, 12.0000, 13.0000])

In [6]:
sample1

tensor([1.3000, 2.0000, 3.0000])

In [7]:
sample1+100

tensor([101.3000, 102.0000, 103.0000])

In [8]:
sample1*10

tensor([13., 20., 30.])

In [9]:
sample1/2

tensor([0.6500, 1.0000, 1.5000])

In [10]:
sample1=sample1*10

In [11]:
sample1

tensor([13., 20., 30.])

In [12]:
# subtract 10


In [13]:
sample1-10

tensor([ 3., 10., 20.])

In [14]:
sample1-20

tensor([-7.,  0., 10.])

In [15]:
## Try out pytorch inbuilt function

In [16]:
torch.mul(sample1,10)

tensor([130., 200., 300.])

In [17]:
torch.add(sample1,200)

tensor([213., 220., 230.])

In [18]:
torch.sub(sample1,1)

tensor([12., 19., 29.])

In [19]:
torch.div(sample1,2)

tensor([ 6.5000, 10.0000, 15.0000])

In [20]:
sample1

tensor([13., 20., 30.])

In [21]:
sample2=torch.rand(1,3)

In [22]:
sample2

tensor([[0.8756, 0.7740, 0.1541]])

In [23]:
torch.mul(sample1,sample2)

tensor([[11.3823, 15.4795,  4.6223]])

In [24]:
sample2

tensor([[0.8756, 0.7740, 0.1541]])

In [25]:
sample1

tensor([13., 20., 30.])

### matric multiplication
## element-wise matmul
## matrix multiplication`(dot product)`

In [26]:
print(f"element wise multiplication {sample1*sample1}")

element wise multiplication tensor([169., 400., 900.])


In [27]:
# matric multiplication

In [28]:
torch.matmul(sample1,sample1)

tensor(1469.)

In [29]:
sample2=torch.rand(3,1)

In [30]:
torch.matmul(sample1,sample2)

tensor([56.0354])

In [31]:
%%timeit
torch.matmul(sample1,sample2)

1.31 μs ± 20.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [32]:
# use torch libraries for the better perfomance

In [33]:
## one of the most common errors in deep learning is shape errors

In [34]:
## the inner dimentions must match match for matrix multiplication
## else it wont work

###### torch.matmul(torch.rand(3,2),torch.rand(3,2))
##### thr above wont work as its innerdomention were not same
### the output matric outer dimention
`(2,3) (3,2)` outer is `(2,2)`

In [35]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.8765, 1.1244, 0.8322],
        [0.5442, 0.7874, 0.5211],
        [0.8499, 1.0975, 0.8073]])

In [36]:
torch.matmul(torch.rand(10,10),torch.rand(10,10)).shape

torch.Size([10, 10])

In [37]:
# one of the most common errors

In [38]:
tensora=torch.tensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
tensorb=torch.tensor([[10,11,12],
                      [13,14,15],
                      [16,17,18]])

In [39]:
tensora,tensorb

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]))

In [40]:
tensora.shape,tensorb.shape

(torch.Size([3, 3]), torch.Size([3, 3]))

In [41]:
%timeit torch.matmul(tensora,tensorb)

783 ns ± 5.66 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [42]:
%timeit torch.mul(tensora,tensorb)

743 ns ± 10.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [43]:
%timeit torch.mm(tensora,tensorb)

762 ns ± 22.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [44]:
## torch.mm was a shortform of matrixmultiplication

In [45]:
tensora=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])
tensorb=torch.tensor([[7,8],
                      [9,10],
                      [11,12]])

In [46]:
torch.matmul(tensora,tensorb)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [47]:
## now to solve /the above problem we should use the transpose function in the torch

In [48]:
## to fix the tensor shape issue
## a transpose will switches the axes 

In [49]:
tensorb=tensorb.T

In [50]:
torch.matmul(tensora,tensorb)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [51]:
tensorb.shape,tensora.shape


(torch.Size([2, 3]), torch.Size([3, 2]))

In [52]:
torch.matmul(tensorb,tensora)

tensor([[ 89, 116],
        [ 98, 128]])

In [53]:
# the matrix multiplication operation works when tensorb transpose

In [54]:
## they do match

In [55]:
## finding the min,max,sum,mean,median etc ## called tensor aggragation

In [56]:
torch.sum(sample1)

tensor(63.)

In [57]:
x=torch.arange(0,100,10)

In [65]:
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [59]:
#sum of elements
torch.sum(x)

tensor(450)

In [60]:
torch.min(x)

tensor(0)

In [61]:
torch.max(x)

tensor(90)

In [67]:
# it is becaule the datatype compatability int64 was also called long 
torch.mean(x.type(torch.float32))

tensor(45.)

In [68]:
#the above demonstates the type cnversion in pytorch

In [70]:
x=x.type(torch.float32)

In [71]:
x.mean()

tensor(45.)

In [72]:
torch.sum(x)

tensor(450.)

In [73]:
%timeit torch.sum(x)


849 ns ± 5.69 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [74]:
%timeit sum(x)

13 μs ± 246 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [75]:
# to fingd the positional min and max

In [76]:
torch.prod(x)

tensor(0.)

In [77]:
torch.std(x)

tensor(30.2765)

In [78]:
torch.var(x)

tensor(916.6667)

In [80]:
## the above were the standard deviation and variance

In [81]:
torch

<module 'torch' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/__init__.py'>

## finding the positional min and max

In [83]:
torch.argmin(x)

tensor(0)

In [84]:
x.argmin()

tensor(0)

In [86]:
torch.argmax(x),x.argmax()

(tensor(9), tensor(9))

In [87]:
## returns the index of the maximum and the minimum

In [88]:
x[0]

tensor(0.)

In [89]:
x[torch.argmin(x)]

tensor(0.)

In [90]:
print('hello')

hello


## reshaping,squeezing,unsqueezing and stacking the tensors

* reshaping- reshes the input tensor to defined shape
* view- return of the input tensor of certain shape but keep the same memory
* stacking- combine multiple tensor horizontally hstack or vertically called vstack

In [91]:
## Types of stacks in tensors

In [92]:
sample1=torch.rand(3,3)

In [93]:
sample2=torch.rand(3,3)

In [96]:

## squeez remove alll 1 dimention from tensor
## unsqueez add 1 dimention to the sensor

In [98]:
torch.vstack((sample1,sample2))

tensor([[0.4595, 0.1452, 0.7611],
        [0.9391, 0.8215, 0.0650],
        [0.3674, 0.9218, 0.4874],
        [0.8319, 0.6554, 0.4724],
        [0.3508, 0.1080, 0.0924],
        [0.1683, 0.3878, 0.6470]])

In [99]:
sample1,sample2

(tensor([[0.4595, 0.1452, 0.7611],
         [0.9391, 0.8215, 0.0650],
         [0.3674, 0.9218, 0.4874]]),
 tensor([[0.8319, 0.6554, 0.4724],
         [0.3508, 0.1080, 0.0924],
         [0.1683, 0.3878, 0.6470]]))

In [100]:
torch.hstack((sample1,sample2))

tensor([[0.4595, 0.1452, 0.7611, 0.8319, 0.6554, 0.4724],
        [0.9391, 0.8215, 0.0650, 0.3508, 0.1080, 0.0924],
        [0.3674, 0.9218, 0.4874, 0.1683, 0.3878, 0.6470]])

In [101]:
## the above will give us the stacking horixontaly and 


In [105]:
sample1.reshape(9),sample1.reshape(9).shape


(tensor([0.4595, 0.1452, 0.7611, 0.9391, 0.8215, 0.0650, 0.3674, 0.9218, 0.4874]),
 torch.Size([9]))

In [106]:
torch.reshape(sample1,(9,1))

tensor([[0.4595],
        [0.1452],
        [0.7611],
        [0.9391],
        [0.8215],
        [0.0650],
        [0.3674],
        [0.9218],
        [0.4874]])

In [107]:
torch.reshape(sample1,(1,9))

tensor([[0.4595, 0.1452, 0.7611, 0.9391, 0.8215, 0.0650, 0.3674, 0.9218, 0.4874]])

In [108]:
# we double the number of elements without doubling the elements

In [109]:
torch.reshape(sample1,(1,9)).shape

torch.Size([1, 9])

In [110]:
#the reshape should be compatable to the original size

In [111]:
x=torch.rand(10)

In [112]:
torch.reshape(x,(5,2))

tensor([[0.5673, 0.8517],
        [0.8216, 0.9824],
        [0.3242, 0.3220],
        [0.4136, 0.4611],
        [0.4079, 0.3720]])

In [113]:
z=sample1.view(9,1)

In [119]:
z


tensor([[1.0000e+02],
        [1.4519e-01],
        [7.6106e-01],
        [9.3914e-01],
        [8.2155e-01],
        [6.4983e-02],
        [3.6739e-01],
        [9.2176e-01],
        [4.8735e-01]])

* view is the similar to the reshape
* But in view the variable shape the data from the original
* any change in the view will result in hange in original
* but not in the case of the case of the reshape

In [115]:
z[0]=100

In [116]:
sample1

tensor([[1.0000e+02, 1.4519e-01, 7.6106e-01],
        [9.3914e-01, 8.2155e-01, 6.4983e-02],
        [3.6739e-01, 9.2176e-01, 4.8735e-01]])

In [120]:
sample2

tensor([[0.8319, 0.6554, 0.4724],
        [0.3508, 0.1080, 0.0924],
        [0.1683, 0.3878, 0.6470]])

In [121]:
sample1

tensor([[1.0000e+02, 1.4519e-01, 7.6106e-01],
        [9.3914e-01, 8.2155e-01, 6.4983e-02],
        [3.6739e-01, 9.2176e-01, 4.8735e-01]])

In [125]:
torch.hstack((sample1,sample2))

tensor([[1.0000e+02, 1.4519e-01, 7.6106e-01, 8.3187e-01, 6.5545e-01, 4.7237e-01],
        [9.3914e-01, 8.2155e-01, 6.4983e-02, 3.5077e-01, 1.0802e-01, 9.2358e-02],
        [3.6739e-01, 9.2176e-01, 4.8735e-01, 1.6831e-01, 3.8778e-01, 6.4698e-01]])

In [123]:
torch.vstack((sample1,sample2))


tensor([[1.0000e+02, 1.4519e-01, 7.6106e-01],
        [9.3914e-01, 8.2155e-01, 6.4983e-02],
        [3.6739e-01, 9.2176e-01, 4.8735e-01],
        [8.3187e-01, 6.5545e-01, 4.7237e-01],
        [3.5077e-01, 1.0802e-01, 9.2358e-02],
        [1.6831e-01, 3.8778e-01, 6.4698e-01]])

In [126]:
x_sample=torch.tensor([1,2,3,4,5])

In [127]:
torch.stack([x_sample,x_sample,x_sample])

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [128]:
torch.stack([x_sample,x_sample,x_sample],dim=1)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]])

In [129]:
torch.stack([x_sample,x_sample,x_sample],dim=1).shape

torch.Size([5, 3])

In [130]:
# squeezing and unsqueezing