In [37]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### The manipulations in Pytorch:
1.Addition
2.Subtraction
3.Multiplication(element-wise)
4.Division
5.Matrix Multiplication

In [38]:
sample1=torch.tensor([1.3,2,3])


In [39]:
sample1+10

tensor([11.3000, 12.0000, 13.0000])

In [40]:
sample1

tensor([1.3000, 2.0000, 3.0000])

In [41]:
sample1+100

tensor([101.3000, 102.0000, 103.0000])

In [42]:
sample1*10

tensor([13., 20., 30.])

In [43]:
sample1/2

tensor([0.6500, 1.0000, 1.5000])

In [44]:
sample1=sample1*10

In [45]:
sample1

tensor([13., 20., 30.])

In [46]:
# subtract 10


In [47]:
sample1-10

tensor([ 3., 10., 20.])

In [48]:
sample1-20

tensor([-7.,  0., 10.])

In [49]:
## Try out pytorch inbuilt function

In [50]:
torch.mul(sample1,10)

tensor([130., 200., 300.])

In [51]:
torch.add(sample1,200)

tensor([213., 220., 230.])

In [52]:
torch.sub(sample1,1)

tensor([12., 19., 29.])

In [53]:
torch.div(sample1,2)

tensor([ 6.5000, 10.0000, 15.0000])

In [54]:
sample1

tensor([13., 20., 30.])

In [55]:
sample2=torch.rand(1,3)

In [56]:
sample2

tensor([[0.6716, 0.0950, 0.5675]])

In [57]:
torch.mul(sample1,sample2)

tensor([[ 8.7312,  1.9006, 17.0241]])

In [58]:
sample2

tensor([[0.6716, 0.0950, 0.5675]])

In [59]:
sample1

tensor([13., 20., 30.])

### matric multiplication
## element-wise matmul
## matrix multiplication`(dot product)`

In [60]:
print(f"element wise multiplication {sample1*sample1}")

element wise multiplication tensor([169., 400., 900.])


In [61]:
# matric multiplication

In [62]:
torch.matmul(sample1,sample1)

tensor(1469.)

In [63]:
sample2=torch.rand(3,1)

In [64]:
torch.matmul(sample1,sample2)

tensor([33.4651])

In [68]:
%%timeit
torch.matmul(sample1,sample2)

1.32 μs ± 13.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [69]:
# use torch libraries for the better perfomance

In [71]:
## one of the most common errors in deep learning is shape errors

In [74]:
## the inner dimentions must match match for matrix multiplication
## else it wont work

###### torch.matmul(torch.rand(3,2),torch.rand(3,2))
##### thr above wont work as its innerdomention were not same
### the output matric outer dimention
`(2,3) (3,2)` outer is `(2,2)`

In [79]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.4284, 0.2345, 0.3230],
        [0.9029, 0.2376, 0.3900],
        [0.9184, 0.3295, 0.4961]])

In [81]:
torch.matmul(torch.rand(10,10),torch.rand(10,10)).shape

torch.Size([10, 10])

In [82]:
# one of the most common errors

In [84]:
tensora=torch.tensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
tensorb=torch.tensor([[10,11,12],
                      [13,14,15],
                      [16,17,18]])

In [85]:
tensora,tensorb

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]))

In [86]:
tensora.shape,tensorb.shape

(torch.Size([3, 3]), torch.Size([3, 3]))

In [90]:
%timeit torch.matmul(tensora,tensorb)

826 ns ± 8.79 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [91]:
%timeit torch.mul(tensora,tensorb)

786 ns ± 7.33 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [95]:
%timeit torch.mm(tensora,tensorb)

778 ns ± 5.36 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [93]:
## torch.mm was a shortform of matrixmultiplication

In [96]:
tensora=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])
tensorb=torch.tensor([[7,8],
                      [9,10],
                      [11,12]])

In [97]:
torch.matmul(tensora,tensorb)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [98]:
## now to solve the above problem we should use the transpose function in the torch

In [99]:
## to fix the tensor shape issue
## a transpose will switches the axes 

In [101]:
tensorb=tensorb.T

In [103]:
torch.matmul(tensora,tensorb)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [105]:
tensorb.shape,tensora.shape


(torch.Size([2, 3]), torch.Size([3, 2]))

In [106]:
torch.matmul(tensorb,tensora)

tensor([[ 89, 116],
        [ 98, 128]])

In [107]:
# the matrix multiplication operation works when tensorb transpose

In [108]:
## they do match