In [132]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### The manipulations in Pytorch:
1.Addition
2.Subtraction
3.Multiplication(element-wise)
4.Division
5.Matrix Multiplication

In [133]:
sample1=torch.tensor([1.3,2,3])


In [134]:
sample1+10

tensor([11.3000, 12.0000, 13.0000])

In [135]:
sample1

tensor([1.3000, 2.0000, 3.0000])

In [136]:
sample1+100

tensor([101.3000, 102.0000, 103.0000])

In [137]:
sample1*10

tensor([13., 20., 30.])

In [138]:
sample1/2

tensor([0.6500, 1.0000, 1.5000])

In [139]:
sample1=sample1*10

In [140]:
sample1

tensor([13., 20., 30.])

In [141]:
# subtract 10


In [142]:
sample1-10

tensor([ 3., 10., 20.])

In [143]:
sample1-20

tensor([-7.,  0., 10.])

In [144]:
## Try out pytorch inbuilt function

In [145]:
torch.mul(sample1,10)

tensor([130., 200., 300.])

In [146]:
torch.add(sample1,200)

tensor([213., 220., 230.])

In [147]:
torch.sub(sample1,1)

tensor([12., 19., 29.])

In [148]:
torch.div(sample1,2)

tensor([ 6.5000, 10.0000, 15.0000])

In [149]:
sample1

tensor([13., 20., 30.])

In [150]:
sample2=torch.rand(1,3)

In [151]:
sample2

tensor([[0.9699, 0.2529, 0.1584]])

In [152]:
torch.mul(sample1,sample2)

tensor([[12.6088,  5.0575,  4.7510]])

In [153]:
sample2

tensor([[0.9699, 0.2529, 0.1584]])

In [154]:
sample1

tensor([13., 20., 30.])

### matric multiplication
## element-wise matmul
## matrix multiplication`(dot product)`

In [155]:
print(f"element wise multiplication {sample1*sample1}")

element wise multiplication tensor([169., 400., 900.])


In [156]:
# matric multiplication

In [157]:
torch.matmul(sample1,sample1)

tensor(1469.)

In [158]:
sample2=torch.rand(3,1)

In [159]:
torch.matmul(sample1,sample2)

tensor([12.3513])

In [160]:
%%timeit
torch.matmul(sample1,sample2)

1.32 μs ± 27.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [161]:
# use torch libraries for the better perfomance

In [162]:
## one of the most common errors in deep learning is shape errors

In [163]:
## the inner dimentions must match match for matrix multiplication
## else it wont work

###### torch.matmul(torch.rand(3,2),torch.rand(3,2))
##### thr above wont work as its innerdomention were not same
### the output matric outer dimention
`(2,3) (3,2)` outer is `(2,2)`

In [164]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.5709, 0.7376, 1.2421],
        [0.3271, 0.5031, 1.0295],
        [0.0619, 0.1041, 0.2299]])

In [165]:
torch.matmul(torch.rand(10,10),torch.rand(10,10)).shape

torch.Size([10, 10])

In [166]:
# one of the most common errors

In [167]:
tensora=torch.tensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
tensorb=torch.tensor([[10,11,12],
                      [13,14,15],
                      [16,17,18]])

In [168]:
tensora,tensorb

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]))

In [169]:
tensora.shape,tensorb.shape

(torch.Size([3, 3]), torch.Size([3, 3]))

In [170]:
%timeit torch.matmul(tensora,tensorb)

782 ns ± 10.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [171]:
%timeit torch.mul(tensora,tensorb)

730 ns ± 4.61 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [172]:
%timeit torch.mm(tensora,tensorb)

728 ns ± 1.22 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [173]:
## torch.mm was a shortform of matrixmultiplication

In [174]:
tensora=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])
tensorb=torch.tensor([[7,8],
                      [9,10],
                      [11,12]])

In [175]:
torch.matmul(tensora,tensorb)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [176]:
## now to solve /the above problem we should use the transpose function in the torch

In [177]:
## to fix the tensor shape issue
## a transpose will switches the axes 

In [178]:
tensorb=tensorb.T

In [179]:
torch.matmul(tensora,tensorb)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [180]:
tensorb.shape,tensora.shape


(torch.Size([2, 3]), torch.Size([3, 2]))

In [181]:
torch.matmul(tensorb,tensora)

tensor([[ 89, 116],
        [ 98, 128]])

In [182]:
# the matrix multiplication operation works when tensorb transpose

In [183]:
## they do match

In [184]:
## finding the min,max,sum,mean,median etc ## called tensor aggragation

In [185]:
torch.sum(sample1)

tensor(63.)

In [186]:
x=torch.arange(0,100,10)

In [187]:
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [188]:
#sum of elements
torch.sum(x)

tensor(450)

In [189]:
torch.min(x)

tensor(0)

In [190]:
torch.max(x)

tensor(90)

In [191]:
# it is becaule the datatype compatability int64 was also called long 
torch.mean(x.type(torch.float32))

tensor(45.)

In [192]:
#the above demonstates the type cnversion in pytorch

In [193]:
x=x.type(torch.float32)

In [194]:
x.mean()

tensor(45.)

In [195]:
torch.sum(x)

tensor(450.)

In [196]:
%timeit torch.sum(x)


843 ns ± 13.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [197]:
%timeit sum(x)

12.7 μs ± 85.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [198]:
# to fingd the positional min and max

In [199]:
torch.prod(x)

tensor(0.)

In [200]:
torch.std(x)

tensor(30.2765)

In [201]:
torch.var(x)

tensor(916.6667)

In [202]:
## the above were the standard deviation and variance

In [203]:
torch

<module 'torch' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/__init__.py'>

## finding the positional min and max

In [204]:
torch.argmin(x)

tensor(0)

In [205]:
x.argmin()

tensor(0)

In [206]:
torch.argmax(x),x.argmax()

(tensor(9), tensor(9))

In [207]:
## returns the index of the maximum and the minimum

In [208]:
x[0]

tensor(0.)

In [209]:
x[torch.argmin(x)]

tensor(0.)

In [210]:
print('hello')

hello


## reshaping,squeezing,unsqueezing and stacking the tensors

* reshaping- reshes the input tensor to defined shape
* view- return of the input tensor of certain shape but keep the same memory
* stacking- combine multiple tensor horizontally hstack or vertically called vstack

In [211]:
## Types of stacks in tensors

In [212]:
sample1=torch.rand(3,3)

In [213]:
sample2=torch.rand(3,3)

In [214]:

## squeez remove alll 1 dimention from tensor
## unsqueez add 1 dimention to the sensor

In [215]:
torch.vstack((sample1,sample2))

tensor([[0.4290, 0.3033, 0.4606],
        [0.1768, 0.9379, 0.5313],
        [0.9231, 0.0044, 0.4718],
        [0.4493, 0.4020, 0.5551],
        [0.6834, 0.9629, 0.2259],
        [0.7403, 0.0846, 0.4374]])

In [216]:
sample1,sample2

(tensor([[0.4290, 0.3033, 0.4606],
         [0.1768, 0.9379, 0.5313],
         [0.9231, 0.0044, 0.4718]]),
 tensor([[0.4493, 0.4020, 0.5551],
         [0.6834, 0.9629, 0.2259],
         [0.7403, 0.0846, 0.4374]]))

In [217]:
torch.hstack((sample1,sample2))

tensor([[0.4290, 0.3033, 0.4606, 0.4493, 0.4020, 0.5551],
        [0.1768, 0.9379, 0.5313, 0.6834, 0.9629, 0.2259],
        [0.9231, 0.0044, 0.4718, 0.7403, 0.0846, 0.4374]])

In [218]:
## the above will give us the stacking horixontaly and 


In [219]:
sample1.reshape(9),sample1.reshape(9).shape


(tensor([0.4290, 0.3033, 0.4606, 0.1768, 0.9379, 0.5313, 0.9231, 0.0044, 0.4718]),
 torch.Size([9]))

In [220]:
torch.reshape(sample1,(9,1))

tensor([[0.4290],
        [0.3033],
        [0.4606],
        [0.1768],
        [0.9379],
        [0.5313],
        [0.9231],
        [0.0044],
        [0.4718]])

In [221]:
torch.reshape(sample1,(1,9))

tensor([[0.4290, 0.3033, 0.4606, 0.1768, 0.9379, 0.5313, 0.9231, 0.0044, 0.4718]])

In [222]:
# we double the number of elements without doubling the elements

In [223]:
torch.reshape(sample1,(1,9)).shape

torch.Size([1, 9])

In [224]:
#the reshape should be compatable to the original size

In [225]:
x=torch.rand(10)

In [226]:
torch.reshape(x,(5,2))

tensor([[0.9255, 0.3253],
        [0.4832, 0.4008],
        [0.0469, 0.7002],
        [0.1381, 0.0106],
        [0.6857, 0.6536]])

In [227]:
z=sample1.view(9,1)

In [228]:
z


tensor([[0.4290],
        [0.3033],
        [0.4606],
        [0.1768],
        [0.9379],
        [0.5313],
        [0.9231],
        [0.0044],
        [0.4718]])

* view is the similar to the reshape
* But in view the variable shape the data from the original
* any change in the view will result in hange in original
* but not in the case of the case of the reshape

In [229]:
z[0]=100

In [230]:
sample1

tensor([[1.0000e+02, 3.0335e-01, 4.6059e-01],
        [1.7677e-01, 9.3794e-01, 5.3126e-01],
        [9.2311e-01, 4.3587e-03, 4.7178e-01]])

In [231]:
sample2

tensor([[0.4493, 0.4020, 0.5551],
        [0.6834, 0.9629, 0.2259],
        [0.7403, 0.0846, 0.4374]])

In [232]:
sample1

tensor([[1.0000e+02, 3.0335e-01, 4.6059e-01],
        [1.7677e-01, 9.3794e-01, 5.3126e-01],
        [9.2311e-01, 4.3587e-03, 4.7178e-01]])

In [233]:
torch.hstack((sample1,sample2))

tensor([[1.0000e+02, 3.0335e-01, 4.6059e-01, 4.4926e-01, 4.0202e-01, 5.5509e-01],
        [1.7677e-01, 9.3794e-01, 5.3126e-01, 6.8344e-01, 9.6294e-01, 2.2587e-01],
        [9.2311e-01, 4.3587e-03, 4.7178e-01, 7.4032e-01, 8.4584e-02, 4.3737e-01]])

In [234]:
torch.vstack([sample1,sample2])


tensor([[1.0000e+02, 3.0335e-01, 4.6059e-01],
        [1.7677e-01, 9.3794e-01, 5.3126e-01],
        [9.2311e-01, 4.3587e-03, 4.7178e-01],
        [4.4926e-01, 4.0202e-01, 5.5509e-01],
        [6.8344e-01, 9.6294e-01, 2.2587e-01],
        [7.4032e-01, 8.4584e-02, 4.3737e-01]])

In [235]:
x_sample=torch.tensor([1,2,3,4,5])

In [236]:
torch.stack([x_sample,x_sample,x_sample])

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [237]:
torch.stack([x_sample,x_sample,x_sample],dim=1)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]])

In [238]:
torch.stack([x_sample,x_sample,x_sample],dim=1).shape

torch.Size([5, 3])

In [239]:
# squeezing and unsqueezing

In [240]:
# squeezing -- temoving al one dim elements from the tensor


In [241]:
x

tensor([0.9255, 0.3253, 0.4832, 0.4008, 0.0469, 0.7002, 0.1381, 0.0106, 0.6857,
        0.6536])

In [243]:
sq=torch.rand(10,1)

In [244]:
sq


tensor([[0.6643],
        [0.9441],
        [0.5088],
        [0.0579],
        [0.4667],
        [0.8594],
        [0.9124],
        [0.4977],
        [0.0933],
        [0.0567]])

In [245]:
sq.squeeze()

tensor([0.6643, 0.9441, 0.5088, 0.0579, 0.4667, 0.8594, 0.9124, 0.4977, 0.0933,
        0.0567])

In [250]:
three=torch.rand(3,1)

In [251]:
three

tensor([[0.9183],
        [0.4077],
        [0.9184]])

In [252]:
torch.squeeze(three)

tensor([0.9183, 0.4077, 0.9184])

In [253]:
three.squeeze()

tensor([0.9183, 0.4077, 0.9184])

In [254]:
## original value but lok different

In [260]:
## un squeeze add the one dimention at a particular position


tensor([[0.9183],
        [0.4077],
        [0.9184]])

In [258]:
torch.unsqueeze(three,0)

tensor([[[0.9183],
         [0.4077],
         [0.9184]]])

In [259]:
three

tensor([[0.9183],
        [0.4077],
        [0.9184]])

In [261]:
s=torch.rand(9)

In [262]:
s

tensor([0.7393, 0.0100, 0.9877, 0.4796, 0.6939, 0.6501, 0.4017, 0.1437, 0.7534])

In [263]:
torch.unsqueeze(s,0)

tensor([[0.7393, 0.0100, 0.9877, 0.4796, 0.6939, 0.6501, 0.4017, 0.1437, 0.7534]])

In [265]:
torch.unsqueeze(s,1)

tensor([[0.7393],
        [0.0100],
        [0.9877],
        [0.4796],
        [0.6939],
        [0.6501],
        [0.4017],
        [0.1437],
        [0.7534]])

In [266]:
#Permuted

In [267]:
## torch.permute used in images


In [268]:
img=torch.rand(3,224,224)

In [270]:
img

tensor([[[0.8652, 0.1955, 0.9243,  ..., 0.6673, 0.9123, 0.8005],
         [0.2905, 0.8237, 0.4101,  ..., 0.8438, 0.6235, 0.4696],
         [0.7787, 0.1450, 0.5319,  ..., 0.3765, 0.8776, 0.0365],
         ...,
         [0.6070, 0.1830, 0.0545,  ..., 0.7901, 0.2141, 0.4815],
         [0.0173, 0.1839, 0.0800,  ..., 0.4773, 0.6764, 0.8141],
         [0.8524, 0.5107, 0.3122,  ..., 0.1678, 0.1877, 0.5401]],

        [[0.7239, 0.8239, 0.7545,  ..., 0.6828, 0.2674, 0.1768],
         [0.0559, 0.9351, 0.6236,  ..., 0.6914, 0.0213, 0.7589],
         [0.4929, 0.3951, 0.7290,  ..., 0.0436, 0.9630, 0.7917],
         ...,
         [0.4883, 0.5409, 0.9361,  ..., 0.3139, 0.7707, 0.8497],
         [0.1400, 0.2477, 0.3732,  ..., 0.1760, 0.9866, 0.0182],
         [0.1984, 0.4854, 0.6832,  ..., 0.9652, 0.2306, 0.0725]],

        [[0.6788, 0.5501, 0.1156,  ..., 0.9039, 0.8815, 0.4176],
         [0.7523, 0.4183, 0.8954,  ..., 0.7913, 0.4307, 0.7122],
         [0.2464, 0.6681, 0.1380,  ..., 0.8297, 0.2842, 0.

In [271]:
# to rearrange the elements
imgp=img.permute(2,0,1)

In [273]:
print(imgp)

tensor([[[0.8652, 0.2905, 0.7787,  ..., 0.6070, 0.0173, 0.8524],
         [0.7239, 0.0559, 0.4929,  ..., 0.4883, 0.1400, 0.1984],
         [0.6788, 0.7523, 0.2464,  ..., 0.6858, 0.4600, 0.6623]],

        [[0.1955, 0.8237, 0.1450,  ..., 0.1830, 0.1839, 0.5107],
         [0.8239, 0.9351, 0.3951,  ..., 0.5409, 0.2477, 0.4854],
         [0.5501, 0.4183, 0.6681,  ..., 0.6863, 0.6087, 0.7266]],

        [[0.9243, 0.4101, 0.5319,  ..., 0.0545, 0.0800, 0.3122],
         [0.7545, 0.6236, 0.7290,  ..., 0.9361, 0.3732, 0.6832],
         [0.1156, 0.8954, 0.1380,  ..., 0.2251, 0.3354, 0.0595]],

        ...,

        [[0.6673, 0.8438, 0.3765,  ..., 0.7901, 0.4773, 0.1678],
         [0.6828, 0.6914, 0.0436,  ..., 0.3139, 0.1760, 0.9652],
         [0.9039, 0.7913, 0.8297,  ..., 0.5043, 0.5737, 0.1576]],

        [[0.9123, 0.6235, 0.8776,  ..., 0.2141, 0.6764, 0.1877],
         [0.2674, 0.0213, 0.9630,  ..., 0.7707, 0.9866, 0.2306],
         [0.8815, 0.4307, 0.2842,  ..., 0.1776, 0.3746, 0.0288]],

 

In [274]:
torch.permute(img,(2,0,1))

tensor([[[0.8652, 0.2905, 0.7787,  ..., 0.6070, 0.0173, 0.8524],
         [0.7239, 0.0559, 0.4929,  ..., 0.4883, 0.1400, 0.1984],
         [0.6788, 0.7523, 0.2464,  ..., 0.6858, 0.4600, 0.6623]],

        [[0.1955, 0.8237, 0.1450,  ..., 0.1830, 0.1839, 0.5107],
         [0.8239, 0.9351, 0.3951,  ..., 0.5409, 0.2477, 0.4854],
         [0.5501, 0.4183, 0.6681,  ..., 0.6863, 0.6087, 0.7266]],

        [[0.9243, 0.4101, 0.5319,  ..., 0.0545, 0.0800, 0.3122],
         [0.7545, 0.6236, 0.7290,  ..., 0.9361, 0.3732, 0.6832],
         [0.1156, 0.8954, 0.1380,  ..., 0.2251, 0.3354, 0.0595]],

        ...,

        [[0.6673, 0.8438, 0.3765,  ..., 0.7901, 0.4773, 0.1678],
         [0.6828, 0.6914, 0.0436,  ..., 0.3139, 0.1760, 0.9652],
         [0.9039, 0.7913, 0.8297,  ..., 0.5043, 0.5737, 0.1576]],

        [[0.9123, 0.6235, 0.8776,  ..., 0.2141, 0.6764, 0.1877],
         [0.2674, 0.0213, 0.9630,  ..., 0.7707, 0.9866, 0.2306],
         [0.8815, 0.4307, 0.2842,  ..., 0.1776, 0.3746, 0.0288]],

 

In [276]:
img[0,0,0]

tensor(0.8652)

In [277]:
imgp[0,0,0]

tensor(0.8652)

In [278]:
# the value didnt change even after the squeezing

In [279]:
## Indexing


In [280]:
img[0,0,0]

tensor(0.8652)

In [281]:
img[:,0,0]

tensor([0.8652, 0.7239, 0.6788])

In [282]:
img[:,:,0]

tensor([[0.8652, 0.2905, 0.7787, 0.9804, 0.9446, 0.0186, 0.3305, 0.0205, 0.2336,
         0.7041, 0.3604, 0.0331, 0.4405, 0.2369, 0.0552, 0.8726, 0.0374, 0.2810,
         0.8940, 0.1475, 0.1781, 0.5661, 0.7113, 0.0529, 0.4142, 0.4541, 0.2234,
         0.2175, 0.6502, 0.1859, 0.3692, 0.7319, 0.2010, 0.1732, 0.7053, 0.1527,
         0.0991, 0.6963, 0.9990, 0.8864, 0.0690, 0.1442, 0.3905, 0.6210, 0.1028,
         0.6386, 0.0695, 0.4627, 0.7351, 0.9338, 0.0755, 0.4945, 0.0857, 0.1886,
         0.3547, 0.6620, 0.8279, 0.1948, 0.7136, 0.1695, 0.1030, 0.5329, 0.7768,
         0.5806, 0.8555, 0.6241, 0.3418, 0.6593, 0.8524, 0.3284, 0.4671, 0.3892,
         0.3270, 0.1438, 0.2467, 0.3043, 0.0426, 0.7661, 0.3146, 0.1312, 0.7787,
         0.9567, 0.2443, 0.6437, 0.5519, 0.1383, 0.6819, 0.0692, 0.8433, 0.2871,
         0.8788, 0.9825, 0.7939, 0.1957, 0.7731, 0.2095, 0.1015, 0.2511, 0.3310,
         0.9616, 0.2628, 0.7835, 0.1323, 0.3218, 0.6356, 0.4931, 0.8892, 0.7625,
         0.2934, 0.3188, 0.5

In [283]:
## indexing in pytorch was similar to the numpy

In [284]:
x=torch.arange(1,10)

In [285]:
x.shape

torch.Size([9])

In [288]:
x=torch.reshape(x,(1,3,3))

In [290]:
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [291]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [297]:
x[0,1],x[0][1]

(tensor([4, 5, 6]), tensor([4, 5, 6]))

In [298]:
x[0,1,1],x[0][1][1]

(tensor(5), tensor(5))

In [299]:
# you can also use the : to select from a range

In [300]:
x[:,0]

tensor([[1, 2, 3]])

In [301]:
x[:,:,1]

tensor([[2, 5, 8]])

In [302]:
# get all values from 0 dimention and only 1 index value of 1st and 2nd dimention

In [303]:
x[:,1,1]

tensor([5])

In [306]:
x[0,0,:],x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [307]:
x[0,2,2]

tensor(9)

In [308]:
x[0,:,2]

tensor([3, 6, 9])

In [310]:
## to convert from the numpy torch.from_numpy()

In [316]:
import numpy as np

In [317]:
n1=np.array([1,2,3,4,5,6,7,8])

In [318]:
t=torch.from_numpy(n1)

In [319]:
t

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [320]:
n1.ndim,t.ndim

(1, 1)

In [321]:
n1.dtype

dtype('int64')

In [322]:
t.dtype

torch.int64

In [323]:
t.type(torch.float32)

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [324]:
## it will produce the new tensor memory rather than mapping

In [325]:
## tensor to numpy
to=torch.ones(3,3)

In [326]:
to

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [327]:
ta=to.numpy()

In [328]:
ta

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

### Reproducability
* trying to take out random from random
* In neural network it works as:
        `start with the random numbers-> tensor operations->update random numbers -> try to make representation again and again`

In [331]:
torch.rand(3,3)

tensor([[0.2970, 0.7849, 0.0895],
        [0.9326, 0.4341, 0.6674],
        [0.1399, 0.6357, 0.9114]])

In [333]:
## pseudo randomness 

In [336]:
ra=torch.rand(3,4)
rb=torch.rand(3,4)
print(ra)
print(rb)
print(ra==rb)

tensor([[0.4613, 0.9180, 0.7742, 0.4114],
        [0.4014, 0.9040, 0.0539, 0.6601],
        [0.1980, 0.0571, 0.8406, 0.4692]])
tensor([[0.3921, 0.6114, 0.3225, 0.5894],
        [0.8406, 0.3864, 0.2973, 0.4916],
        [0.2706, 0.9380, 0.3432, 0.4056]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [337]:
## no values of the random tensor would match

In [338]:
# through concept of random seed

In [342]:
#randomseed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
randoms=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
randomss=torch.rand(3,4)
print(randoms)
print(randomss)
print(randoms==randomss)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [343]:
## by random seed we will get the same random values 