In [1]:
import torch
from torch import nn
import numpy as np
import pandas as pd


In [2]:
device='mps' if torch.backends.mps.is_available() else 'cpu'
x=np.arange(0,1,0.01)
y=0.8*(x**2)
limit=int(0.8*len(x))
x_train=torch.from_numpy(x[:int(0.8*len(x))]).type(torch.float32).to(device)
y_train=torch.from_numpy(y[:int(0.8*len(x))]).type(torch.float32).to(device)
x_test=torch.from_numpy(x[int(0.8*len(x)):]).type(torch.float32).to(device)
y_test=torch.from_numpy(y[int(0.8*len(x)):]).type(torch.float32).to(device)

In [3]:
y

array([0.0000e+00, 8.0000e-05, 3.2000e-04, 7.2000e-04, 1.2800e-03,
       2.0000e-03, 2.8800e-03, 3.9200e-03, 5.1200e-03, 6.4800e-03,
       8.0000e-03, 9.6800e-03, 1.1520e-02, 1.3520e-02, 1.5680e-02,
       1.8000e-02, 2.0480e-02, 2.3120e-02, 2.5920e-02, 2.8880e-02,
       3.2000e-02, 3.5280e-02, 3.8720e-02, 4.2320e-02, 4.6080e-02,
       5.0000e-02, 5.4080e-02, 5.8320e-02, 6.2720e-02, 6.7280e-02,
       7.2000e-02, 7.6880e-02, 8.1920e-02, 8.7120e-02, 9.2480e-02,
       9.8000e-02, 1.0368e-01, 1.0952e-01, 1.1552e-01, 1.2168e-01,
       1.2800e-01, 1.3448e-01, 1.4112e-01, 1.4792e-01, 1.5488e-01,
       1.6200e-01, 1.6928e-01, 1.7672e-01, 1.8432e-01, 1.9208e-01,
       2.0000e-01, 2.0808e-01, 2.1632e-01, 2.2472e-01, 2.3328e-01,
       2.4200e-01, 2.5088e-01, 2.5992e-01, 2.6912e-01, 2.7848e-01,
       2.8800e-01, 2.9768e-01, 3.0752e-01, 3.1752e-01, 3.2768e-01,
       3.3800e-01, 3.4848e-01, 3.5912e-01, 3.6992e-01, 3.8088e-01,
       3.9200e-01, 4.0328e-01, 4.1472e-01, 4.2632e-01, 4.3808e

In [6]:
class regression(nn.Module):
    def __init__(self):
        super().__init__()
        self.weight=nn.Parameter(torch.rand(1,requires_grad=True,dtype=torch.float32))
        print(self.weight)
    def forward(self,x):
        return self.weight*(x**2)
    





In [7]:
torch.manual_seed(42)
model=regression()
loss_fn=nn.L1Loss()
optimizer=torch.optim.SGD(params=model.parameters(),lr=0.01)
model.state_dict()
list(model.parameters())

Parameter containing:
tensor([0.8823], requires_grad=True)


[Parameter containing:
 tensor([0.8823], requires_grad=True)]

In [8]:
epochs=100
for epoch in range(epochs):
    model.train()
    y_p=model(x_train)
    loss=loss_fn(y_p,y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!

In [9]:
print(loss)

NameError: name 'loss' is not defined