In [75]:
import torch 
import torchvision
from torchvision import datasets,transforms
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt
from torch import nn

In [77]:
train_data=datasets.FashionMNIST(root='data',
                                 train=True,
                                 download=True,
                                 transform=ToTensor(),
                                 target_transform=None)
test_data=datasets.FashionMNIST(root='data',
                                train=False,
                                download=True,
                                transform=ToTensor(),
                                target_transform=None)

In [79]:
train_data[0]

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0039, 0.0000, 0.0000, 0.0510,
           0.2863, 0.0000, 0.0000, 0.0039, 

In [81]:
plt.figure(figsize=(10,10),dpi=1000)
img,l=train_data[0]
plt.imshow(img.squeeze(),cmap='gray')
plt.axis(False)

(-0.5, 27.5, 27.5, -0.5)

In [82]:
from torch.utils.data import DataLoader
train_dataloader=DataLoader(dataset=train_data,
                            batch_size=32,
                            shuffle=True)

test_dataloader=DataLoader(dataset=test_data,
                           batch_size=32,
                           shuffle=False)

In [83]:
len(iter(train_dataloader))

1875

In [84]:
train_features,train_labels=next(iter(train_dataloader))

In [85]:
train_features

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        ...,


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0.

In [86]:
train_features.shape

torch.Size([32, 1, 28, 28])

In [87]:
len(train_features)

32

In [88]:
x=train_features[0]

In [89]:
x.shape


torch.Size([1, 28, 28])

In [90]:
flatten_model=nn.Flatten()
output=flatten_model(x)

In [105]:
output.shape

torch.Size([1, 784])

In [107]:
output

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.5098, 0.4588, 0.3137, 0.3294, 0.4667, 0.6353, 0.2588,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.2667, 0.7725, 0.9373, 0.9961, 0.9804, 0.6000, 0.6353, 1.0000, 1.0000,
         0.9176, 0.8745, 0.8275, 0.1294, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0078, 0.0000,
         0.3020, 0.9569, 0.9176, 0.8667, 0.8863, 0.9569, 0.9804, 0.9686, 0.9490,
         0.8902, 0.8314, 0.8745, 0.9137, 0.8510, 0.0000, 0.0000, 0.0078, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.7098, 0.9294, 0.8471, 0.8588, 0.8471, 0.9490, 0.9451, 0.9294,
         0.9647, 0.8471, 0.8588, 0.8784, 0.8353, 0.9569, 0.4392, 0.0000, 0.0118,
         0.0000, 0.0000, 0.0

In [109]:
class FashionMNIST(nn.Module):
    def __init__(self,input_shape:int,output_shape:int):
        super().__init__()
        self.stack=nn.Sequential(
                                    nn.Linear(in_features=input_shape,out_features=10),
                                    nn.ReLU(),
                                    nn.Linear(in_features=10,out_features=output_shape)
        )
    def forward(self,x):
        return self.stack(x)
        

In [111]:
model=FashionMNIST(output.shape[1],9)


In [113]:
model.state_dict()

OrderedDict([('stack.0.weight',
              tensor([[-0.0278,  0.0036,  0.0330,  ..., -0.0093, -0.0186, -0.0126],
                      [-0.0017,  0.0247,  0.0189,  ..., -0.0109, -0.0333,  0.0240],
                      [-0.0226,  0.0018, -0.0195,  ..., -0.0134,  0.0154,  0.0151],
                      ...,
                      [-0.0271,  0.0225, -0.0079,  ..., -0.0243,  0.0282, -0.0201],
                      [-0.0092, -0.0041, -0.0129,  ...,  0.0274,  0.0110,  0.0343],
                      [ 0.0168,  0.0235,  0.0179,  ..., -0.0132,  0.0124, -0.0172]])),
             ('stack.0.bias',
              tensor([-0.0318,  0.0269, -0.0282, -0.0149,  0.0335, -0.0337,  0.0336,  0.0258,
                       0.0101, -0.0063])),
             ('stack.2.weight',
              tensor([[ 0.2860,  0.0774, -0.1678,  0.2787, -0.2927,  0.1473,  0.1065, -0.2469,
                        0.0700, -0.0677],
                      [ 0.1895, -0.3001, -0.0316, -0.0214, -0.2291,  0.0737, -0.2275, -0.2077,
   

In [115]:
y=model(output.squeeze())

In [117]:
y

tensor([-0.0276, -0.0168, -0.2823,  0.2155,  0.2675,  0.2646, -0.3938, -0.1018,
         0.2627], grad_fn=<ViewBackward0>)

In [119]:
y.argmax()

tensor(4)