In [101]:
import torch
from torch import nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# Pytorch basic workflow
* Lets explore example pytorch end-to-end workflow

1. Get Data Ready
2. Prepare and Load
3. Build Model
4. Fitting the model(Training)
5. Making Predictions and evaluation (inference)
6. save and load a model

In [102]:
# nn contains all of the pytorch building blocks for neural network

In [103]:
## we can virtualy build any neural network

In [104]:
torch.__version__

'2.4.1'

In [105]:
torch.backends.mps.is_available()

True

In [106]:
torch.cuda.is_available()

False

# 1.Data Preparing and loading

In [107]:
## dara preparing and loading

## 1. Data can be anything in ML
1. excel
2. images
3. videos
4. audio
5. DNA
6. TEXT

## Machine learning

1. Get data into numerical representation
2. build a model to learn patterns in numerical representations

In [108]:
## 1.inputs
## 2. numerical data
## 3.numerical network 
## 4.output(regression or classificaction)

In [109]:
## to showcaase this create some known data 

In [110]:
# linear regression

In [111]:
## we make a linear regression formulae to with the known parameter


In [112]:
# create *known* parameters


In [113]:
weight=0.7
bias=0.3

# create data
start=0
end=1
step=0.02
X=torch.arange(start,end,step).unsqueeze(dim=1)

In [114]:
torch.linspace(0,1,100)

tensor([0.0000, 0.0101, 0.0202, 0.0303, 0.0404, 0.0505, 0.0606, 0.0707, 0.0808,
        0.0909, 0.1010, 0.1111, 0.1212, 0.1313, 0.1414, 0.1515, 0.1616, 0.1717,
        0.1818, 0.1919, 0.2020, 0.2121, 0.2222, 0.2323, 0.2424, 0.2525, 0.2626,
        0.2727, 0.2828, 0.2929, 0.3030, 0.3131, 0.3232, 0.3333, 0.3434, 0.3535,
        0.3636, 0.3737, 0.3838, 0.3939, 0.4040, 0.4141, 0.4242, 0.4343, 0.4444,
        0.4545, 0.4646, 0.4747, 0.4848, 0.4949, 0.5051, 0.5152, 0.5253, 0.5354,
        0.5455, 0.5556, 0.5657, 0.5758, 0.5859, 0.5960, 0.6061, 0.6162, 0.6263,
        0.6364, 0.6465, 0.6566, 0.6667, 0.6768, 0.6869, 0.6970, 0.7071, 0.7172,
        0.7273, 0.7374, 0.7475, 0.7576, 0.7677, 0.7778, 0.7879, 0.7980, 0.8081,
        0.8182, 0.8283, 0.8384, 0.8485, 0.8586, 0.8687, 0.8788, 0.8889, 0.8990,
        0.9091, 0.9192, 0.9293, 0.9394, 0.9495, 0.9596, 0.9697, 0.9798, 0.9899,
        1.0000])

In [115]:
X

tensor([[0.0000],
        [0.0200],
        [0.0400],
        [0.0600],
        [0.0800],
        [0.1000],
        [0.1200],
        [0.1400],
        [0.1600],
        [0.1800],
        [0.2000],
        [0.2200],
        [0.2400],
        [0.2600],
        [0.2800],
        [0.3000],
        [0.3200],
        [0.3400],
        [0.3600],
        [0.3800],
        [0.4000],
        [0.4200],
        [0.4400],
        [0.4600],
        [0.4800],
        [0.5000],
        [0.5200],
        [0.5400],
        [0.5600],
        [0.5800],
        [0.6000],
        [0.6200],
        [0.6400],
        [0.6600],
        [0.6800],
        [0.7000],
        [0.7200],
        [0.7400],
        [0.7600],
        [0.7800],
        [0.8000],
        [0.8200],
        [0.8400],
        [0.8600],
        [0.8800],
        [0.9000],
        [0.9200],
        [0.9400],
        [0.9600],
        [0.9800]])

In [116]:
Y=weight*X+bias
Y

tensor([[0.3000],
        [0.3140],
        [0.3280],
        [0.3420],
        [0.3560],
        [0.3700],
        [0.3840],
        [0.3980],
        [0.4120],
        [0.4260],
        [0.4400],
        [0.4540],
        [0.4680],
        [0.4820],
        [0.4960],
        [0.5100],
        [0.5240],
        [0.5380],
        [0.5520],
        [0.5660],
        [0.5800],
        [0.5940],
        [0.6080],
        [0.6220],
        [0.6360],
        [0.6500],
        [0.6640],
        [0.6780],
        [0.6920],
        [0.7060],
        [0.7200],
        [0.7340],
        [0.7480],
        [0.7620],
        [0.7760],
        [0.7900],
        [0.8040],
        [0.8180],
        [0.8320],
        [0.8460],
        [0.8600],
        [0.8740],
        [0.8880],
        [0.9020],
        [0.9160],
        [0.9300],
        [0.9440],
        [0.9580],
        [0.9720],
        [0.9860]])

In [117]:
X[:10],Y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [118]:
len(X)
len(Y)


50

### Splitting of the data into the training and the test sets (one of the important concepts in Mahine Learning)

## three Datasets
## traingin set
## validation set
## test set

* 100 ->  70 for training 
        15 validation
        15 for the test

In [119]:
## ability of the training model to perform well on the things which it hasnt seen before

In [120]:
## you can omit validation set sometimes

In [121]:
# create train/test spllit



In [122]:
train_split=int(0.8*len(X))
train_split

40

In [123]:
X_train=X[:train_split]
Y_train=Y[:train_split]
X_test=X[train_split:]
Y_test=Y[train_split:]

In [124]:
len(X_train),len(X_test)

(40, 10)

In [125]:
## Building a function to visualize

In [126]:
len(X_train),X_test

(40,
 tensor([[0.8000],
         [0.8200],
         [0.8400],
         [0.8600],
         [0.8800],
         [0.9000],
         [0.9200],
         [0.9400],
         [0.9600],
         [0.9800]]))

In [127]:
def plot_predictions(train_data=X_train,train_labels=Y_train,test_data=X_test,test_labels=Y_test,predictions=None):

    plt.figure(figsize=(10,7),dpi=1000)
    plt.scatter(train_data,train_labels,color='blue',label="training data")
    
    ## testing data
    plt.scatter(test_data,test_labels,color='green',label="testing data")
    plt.legend()

    if predictions is not None:
        plt.scatter(test_data,predictions,c='red',label='predictions')
        plt.legend()
    

In [128]:
plot_predictions()

In [129]:
Y

tensor([[0.3000],
        [0.3140],
        [0.3280],
        [0.3420],
        [0.3560],
        [0.3700],
        [0.3840],
        [0.3980],
        [0.4120],
        [0.4260],
        [0.4400],
        [0.4540],
        [0.4680],
        [0.4820],
        [0.4960],
        [0.5100],
        [0.5240],
        [0.5380],
        [0.5520],
        [0.5660],
        [0.5800],
        [0.5940],
        [0.6080],
        [0.6220],
        [0.6360],
        [0.6500],
        [0.6640],
        [0.6780],
        [0.6920],
        [0.7060],
        [0.7200],
        [0.7340],
        [0.7480],
        [0.7620],
        [0.7760],
        [0.7900],
        [0.8040],
        [0.8180],
        [0.8320],
        [0.8460],
        [0.8600],
        [0.8740],
        [0.8880],
        [0.9020],
        [0.9160],
        [0.9300],
        [0.9440],
        [0.9580],
        [0.9720],
        [0.9860]])

## Building up the pytorch model
* start with the random values (weight and bias)
* look at training values
* adjust the weights and get to the closer to ideal values
* By gradient descent and backpropagation

In [137]:
# create a linear regression model class
class LinearRegressionModel(nn.Module):

    #inherits from nn.module
    #al most everything from pytorch model

    #modules could contain other modules
    def __init__(self):
        super().__init__()
        self.weights=nn.Parameter(torch.randn(1,requires_grad=True,dtype=torch.float32))

        self.bias=nn.Parameter(torch.randn(1,requirs_grad=True,dtype=torch.float32))

    def forword(self,x:torch.Tensor)->torch.Tensor:
        return self.weights*X+self.bias
        

In [138]:
#torch.sum(torch.mul(torch.tensor([1,2,3]),torch.tensor([1,2,3])))

In [139]:
## there is an another nn module through which we can set the initial w and bias values

In [140]:
#nn.Module contains all building blocks

In [141]:
## for bigger models we neednot initialize the weights explicitly

In [142]:
## torch.autograd will work 

In [143]:
# we requre forword method()

In [144]:
## forword module will give us the computations of the model


## Pytorch model building essentials
* torch.nn conataines all the building blocks for neuralnetwork(computational graph)
* torch.parameter wills set the parameter for the neural network layer
* torch.optim -- this wil optimizein pytorch
* def forword() -- all nnModule subsclasses require you to iverwrite the forword() defines what hapend in forword computation
  

In [147]:
print('aditya')

aditya


In [148]:
## checkout the internals in pytorch